import {FormEvent,useState} from 'react';
import {Eye,EyeOff,KeyRound,LockKeyhole,ShieldCheck} from 'lucide-react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {apiFetch} from '../../services/api/client';

export function ResetPasswordPage(){
 const [params]=useSearchParams(); const navigate=useNavigate(); const [token,setToken]=useState(params.get('token')||''); const [senha,setSenha]=useState(''); const [confirmar,setConfirmar]=useState(''); const [mostrar,setMostrar]=useState(false); const [erro,setErro]=useState(''); const [ok,setOk]=useState(''); const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setErro('');setOk('');if(senha!==confirmar){setErro('As senhas não conferem.');return;}setLoading(true);try{const r=await apiFetch<{mensagem:string}>('/api/v1/auth/redefinir-senha',{method:'POST',body:JSON.stringify({token,nova_senha:senha,confirmar_senha:confirmar})});setOk(r.mensagem);setTimeout(()=>navigate('/login'),1000)}catch(x){setErro(x instanceof Error?x.message:'Não foi possível redefinir a senha.')}finally{setLoading(false)}}
 return <main className="login-page"><section className="login-brand"><div className="login-brand-mark">Ω</div><h1>ÔMEGA</h1><p>Defina uma nova senha.</p><div className="login-points"><span><ShieldCheck size={16}/> Token temporário e de uso único</span><span><KeyRound size={16}/> Senha com no mínimo 8 caracteres</span></div></section><section className="login-card"><div><span className="eyebrow">SEGURANÇA</span><h2>Redefinir senha</h2><p>Informe a nova senha da sua conta.</p></div>{erro&&<div className="form-error">{erro}</div>}{ok&&<div className="form-success">{ok}</div>}<form onSubmit={submit} className="login-form"><label>Token<div className="login-input"><KeyRound size={17}/><input value={token} onChange={e=>setToken(e.target.value)} required/></div></label><label>Nova senha<div className="login-input"><LockKeyhole size={17}/><input type={mostrar?'text':'password'} value={senha} onChange={e=>setSenha(e.target.value)} minLength={8} autoComplete="new-password" required/><button type="button" className="password-toggle" onClick={()=>setMostrar(v=>!v)}>{mostrar?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label><label>Confirmar senha<div className="login-input"><LockKeyhole size={17}/><input type={mostrar?'text':'password'} value={confirmar} onChange={e=>setConfirmar(e.target.value)} minLength={8} autoComplete="new-password" required/></div></label><button className="button primary login-submit" disabled={loading}>{loading?'Salvando...':'Salvar nova senha'}</button></form><div className="auth-links"><Link to="/login">Voltar para login</Link><span>•</span><Link to="/registrar">Criar conta</Link></div></section></main>;
}
