import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Building2,CheckCircle2,Clock3,Info,Landmark,Plus,Save,WalletCards,X} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {Loading} from '../../components/ui/Loading';
import {ErrorState} from '../../components/ui/ErrorState';
import {listarTributos,obterEmpresaImpostos,registrarImposto,vincularTributo,type EmpresaImpostos,type Tributo} from '../../services/api/impostos';
import './Impostos.css';
function dinheiro(v:number|undefined|null){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));}
function dataBr(v?:string|null){if(!v)return '—'; const [a,m,d]=v.split('-'); return `${d}/${m}/${a}`;}
function hojeAnterior(){const h=new Date();return h.getMonth()===0?{ano:h.getFullYear()-1,mes:12}:{ano:h.getFullYear(),mes:h.getMonth()};}
export function EmpresaImpostosPage(){const {id}=useParams();const empresaId=Number(id);const [ano,setAno]=useState(hojeAnterior().ano);const [mes,setMes]=useState(hojeAnterior().mes);const [data,setData]=useState<EmpresaImpostos|null>(null);const [tributos,setTributos]=useState<Tributo[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [vincularOpen,setVincularOpen]=useState(false);const [registrarOpen,setRegistrarOpen]=useState(false);const [tributoId,setTributoId]=useState('');const [status,setStatus]=useState('PENDENTE');const [valor,setValor]=useState('');const [vencimento,setVencimento]=useState('');const [pagamento,setPagamento]=useState('');const [documento,setDocumento]=useState('');const [saving,setSaving]=useState(false);const [success,setSuccess]=useState('');
 async function load(){setLoading(true);setError('');try{const [d,t]=await Promise.all([obterEmpresaImpostos(empresaId,ano,mes),listarTributos()]);setData(d);setTributos(t.tributos);}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar impostos.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[empresaId,ano,mes]);
 const disponiveis=useMemo(()=>tributos.filter(t=>!data?.tributos.some(x=>x.tributo_id===t.id)),[tributos,data]);
 async function salvarVinculo(){if(!tributoId)return;setSaving(true);setError('');try{await vincularTributo(empresaId,{tributo_id:Number(tributoId),obrigatorio:true});setVincularOpen(false);setTributoId('');setSuccess('Tributo vinculado com sucesso.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível vincular o tributo.');}finally{setSaving(false);}}
 async function salvarMensal(){if(!tributoId){setError('Selecione o tributo.');return;}setSaving(true);setError('');try{await registrarImposto(empresaId,{tributo_id:Number(tributoId),competencia_ano:ano,competencia_mes:mes,status,valor:valor===''?null:Number(valor),data_vencimento:vencimento||null,data_pagamento:pagamento||null,numero_documento:documento||null});setRegistrarOpen(false);setTributoId('');setValor('');setVencimento('');setPagamento('');setDocumento('');setSuccess('Competência registrada com sucesso.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar o imposto.');}finally{setSaving(false);}}
 if(loading)return <div className="page"><Loading/></div>; if(error&&!data)return <div className="page"><ErrorState message={error} onRetry={()=>void load()}/></div>; if(!data)return null;
 return <div className="page impostos-page"><Link to="/impostos" className="back-link"><ArrowLeft size={15}/> Voltar para Impostos</Link><div className="imp-company-heading"><div className="imp-company-identification"><span className="imp-company-icon"><Building2 size={19}/></span><div><span className="eyebrow">EMPRESA</span><h2>{data.empresa.razao_social}</h2><div className="imp-detail-meta">{data.empresa.cnpj} · {data.empresa.regime_tributario||'Regime não informado'}{data.empresa.municipio?` · ${data.empresa.municipio}/${data.empresa.uf||''}`:''}</div></div></div><Link className="button secondary" to={`/empresas/${empresaId}`}><Info size={14}/> Informações da empresa</Link></div>{error&&<div className="form-error imp-error">{error}</div>}{success&&<div className="imp-success"><CheckCircle2 size={17}/><span>{success}</span><button className="icon-button" onClick={()=>setSuccess('')}><X size={14}/></button></div>}
 <div className="imp-detail-summary"><div className="imp-detail-card"><span className="imp-metric-icon purple"><Landmark size={17}/></span><div><strong>{data.resumo.tributos_vinculados}</strong><small>Tributos vinculados</small></div></div><div className="imp-detail-card"><span className="imp-metric-icon amber"><Clock3 size={17}/></span><div><strong>{data.resumo.pendentes}</strong><small>Pendentes na competência</small></div></div><div className="imp-detail-card"><span className="imp-metric-icon green"><CheckCircle2 size={17}/></span><div><strong>{data.resumo.pagos}</strong><small>Pagos na competência</small></div></div><div className="imp-detail-card"><span className="imp-metric-icon blue"><WalletCards size={17}/></span><div><strong>{dinheiro(data.resumo.valor_a_pagar)}</strong><small>Valor a pagar</small><em>{data.competencia.label}</em></div></div></div>
 <div className="panel imp-section"><div className="imp-section-head"><div><span className="eyebrow">ACOMPANHAMENTO MENSAL</span><h3>{data.competencia.label}</h3></div><div className="imp-section-actions"><button className="button secondary" onClick={()=>setVincularOpen(true)}><Plus size={14}/> Vincular tributo</button><button className="button primary" onClick={()=>{setTributoId(data.tributos[0]?.tributo_id?String(data.tributos[0].tributo_id):'');setRegistrarOpen(true)}} disabled={!data.tributos.length}><Save size={14}/> Registrar competência</button></div></div><div className="imp-year-toolbar"><button className="icon-button" onClick={()=>setAno(x=>x-1)}>‹</button><strong>{ano}</strong><button className="icon-button" onClick={()=>setAno(x=>x+1)}>›</button><select value={mes} onChange={e=>setMes(Number(e.target.value))}>{['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'].map((x,i)=><option key={i+1} value={i+1}>{x}</option>)}</select></div><div className="imp-tax-list">{data.tributos.map(item=><div className="imp-tax-card" key={item.vinculo_id}><div className="imp-tax-main"><span className="imp-tax-icon"><Landmark size={16}/></span><div><strong>{item.nome}{item.sigla?` (${item.sigla})`:''}</strong><small>{item.esfera||'Esfera não informada'} · {item.periodicidade||'Periodicidade não informada'}</small></div></div><div className="imp-tax-values"><span className={`imp-status ${item.status_mensal==='PAGO'?'done':'pending'}`}><i/> {item.status_mensal||'PENDENTE'}</span><strong>{item.valor!=null?dinheiro(item.valor):'—'}</strong><small>Venc. {dataBr(item.data_vencimento)}</small></div><button className="button ghost" onClick={()=>{setTributoId(String(item.tributo_id));setStatus(item.status_mensal||'PENDENTE');setValor(item.valor!=null?String(item.valor):'');setVencimento(item.data_vencimento||'');setPagamento(item.data_pagamento||'');setDocumento(item.numero_documento||'');setRegistrarOpen(true)}}>Editar</button></div>)}{!data.tributos.length&&<div className="imp-empty big"><Landmark size={27}/><strong>Nenhum tributo vinculado</strong><span>Comece vinculando os tributos aplicáveis a esta empresa.</span><button className="button primary" onClick={()=>setVincularOpen(true)}><Plus size={14}/> Vincular primeiro tributo</button></div>}</div></div>
 {vincularOpen&&<div className="modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setVincularOpen(false)}}><div className="modal imp-modal"><div className="modal-head"><div><span className="eyebrow">EMPRESA</span><h3>Vincular tributo</h3></div><button className="icon-button" onClick={()=>setVincularOpen(false)}>×</button></div><div className="modal-body"><label className="imp-modal-label">Tributo<select value={tributoId} onChange={e=>setTributoId(e.target.value)}><option value="">Selecione</option>{disponiveis.map(t=><option key={t.id} value={t.id}>{t.nome}{t.sigla?` (${t.sigla})`:''}</option>)}</select></label>{!disponiveis.length&&<div className="imp-inline-note">Todos os tributos cadastrados já estão vinculados a esta empresa.</div>}</div><div className="modal-actions"><button className="button secondary" onClick={()=>setVincularOpen(false)}>Cancelar</button><button className="button primary" disabled={saving||!tributoId} onClick={()=>void salvarVinculo()}>{saving?'Salvando...':'Vincular tributo'}</button></div></div></div>}
 {registrarOpen&&<div className="modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setRegistrarOpen(false)}}><div className="modal imp-modal"><div className="modal-head"><div><span className="eyebrow">COMPETÊNCIA {String(mes).padStart(2,'0')}/{ano}</span><h3>Registrar imposto</h3></div><button className="icon-button" onClick={()=>setRegistrarOpen(false)}>×</button></div><div className="modal-body"><div className="form-grid"><label>Tributo<select value={tributoId} onChange={e=>setTributoId(e.target.value)}>{data.tributos.map(t=><option key={t.tributo_id} value={t.tributo_id}>{t.nome}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>PENDENTE</option><option>PAGO</option><option>DISPENSADO</option><option>SEM MOVIMENTO</option></select></label><label>Valor<input type="number" step="0.01" min="0" value={valor} onChange={e=>setValor(e.target.value)} placeholder="0,00"/></label><label>Vencimento<input type="date" value={vencimento} onChange={e=>setVencimento(e.target.value)}/></label><label>Pagamento<input type="date" value={pagamento} onChange={e=>setPagamento(e.target.value)}/></label><label>Documento<input value={documento} onChange={e=>setDocumento(e.target.value)} placeholder="Nº do documento/guia"/></label></div></div><div className="modal-actions"><button className="button secondary" onClick={()=>setRegistrarOpen(false)}>Cancelar</button><button className="button primary" disabled={saving||!tributoId} onClick={()=>void salvarMensal()}>{saving?'Salvando...':'Salvar competência'}</button></div></div></div>}
 </div>;
}
