import {useEffect,useMemo,useState} from 'react';
import {Building2,CheckCircle2,Clock3,Landmark,Plus,Search,WalletCards,ChevronRight} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {Loading} from '../../components/ui/Loading';
import {ErrorState} from '../../components/ui/ErrorState';
import {criarTributo,listarImpostos,listarTributos,type DashboardImpostos,type Tributo} from '../../services/api/impostos';
import './Impostos.css';

const REGIMES=[{value:'TODOS',label:'Todas',className:'all'},{value:'SIMPLES NACIONAL',label:'Simples Nacional',className:'simples'},{value:'LUCRO PRESUMIDO',label:'Lucro Presumido',className:'presumido'},{value:'LUCRO REAL',label:'Lucro Real',className:'real'}];
function dinheiro(v:number|undefined|null){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));}
function regimeClass(v?:string|null){const x=(v||'').toLowerCase();return x.includes('simples')?'simples':x.includes('presumido')?'presumido':x.includes('real')?'real':'neutral';}
export function ImpostosPage(){
 const [data,setData]=useState<DashboardImpostos|null>(null); const [regime,setRegime]=useState('TODOS'); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [novoOpen,setNovoOpen]=useState(false); const [nome,setNome]=useState(''); const [sigla,setSigla]=useState(''); const [esfera,setEsfera]=useState(''); const [periodicidade,setPeriodicidade]=useState('Mensal'); const [saving,setSaving]=useState(false); const [tributos,setTributos]=useState<Tributo[]>([]); const navigate=useNavigate();
 async function load(){setLoading(true);setError('');try{const [dashboard, catalogo]=await Promise.all([listarImpostos({regime,q}),listarTributos()]);setData(dashboard);setTributos(catalogo.tributos);}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar impostos.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[regime]);
 const visible=useMemo(()=>{const t=q.trim().toLowerCase();return (data?.empresas||[]).filter(x=>!t||`${x.razao_social} ${x.nome_fantasia||''} ${x.cnpj}`.toLowerCase().includes(t));},[data,q]);
 async function salvarTributo(){if(!nome.trim()){setError('Informe o nome do tributo.');return;}setSaving(true);setError('');try{await criarTributo({nome:nome.trim(),sigla:sigla.trim()||null,esfera:esfera||null,periodicidade:periodicidade||null});const catalogo=await listarTributos();setTributos(catalogo.tributos);setNovoOpen(false);setNome('');setSigla('');setEsfera('');setPeriodicidade('Mensal');}catch(e){setError(e instanceof Error?e.message:'Não foi possível cadastrar o tributo.');}finally{setSaving(false);}}
 if(loading)return <div className="page"><Loading/></div>; if(error&&!data)return <div className="page"><ErrorState message={error} onRetry={()=>void load()}/></div>; if(!data)return null;
 return <div className="page impostos-page">
   <div className="page-heading"><div><span className="eyebrow">CONTROLE TRIBUTÁRIO</span><h2><Landmark size={25}/> Impostos</h2><p>Acompanhe tributos, competências e valores das empresas em um único painel.</p></div><button className="button imp-main-action" onClick={()=>setNovoOpen(true)}><Plus size={15}/> Novo tributo</button></div>
   {error&&<div className="form-error imp-error">{error}</div>}
   <div className="imp-metrics-grid"><div className="imp-metric-card"><span className="imp-metric-icon blue"><Building2 size={18}/></span><div><strong>{data.indicadores.total_empresas}</strong><small>Empresas</small></div></div><div className="imp-metric-card"><span className="imp-metric-icon purple"><Landmark size={18}/></span><div><strong>{data.indicadores.empresas_configuradas}</strong><small>Com tributos configurados</small></div></div><div className="imp-metric-card"><span className="imp-metric-icon amber"><Clock3 size={18}/></span><div><strong>{data.indicadores.impostos_pendentes}</strong><small>Impostos pendentes</small></div></div><div className="imp-metric-card"><span className="imp-metric-icon green"><WalletCards size={18}/></span><div><strong>{dinheiro(data.indicadores.valor_a_pagar)}</strong><small>Valor a pagar</small><em>{data.competencia.label}</em></div></div></div>
   <section className="panel imp-tax-catalog"><div className="imp-catalog-head"><div><span className="eyebrow">CADASTRO GLOBAL</span><h3>Tributos cadastrados</h3><p>Tributos disponíveis para vinculação às empresas.</p></div><span className="imp-catalog-count">{tributos.length} cadastrado{tributos.length===1?'':'s'}</span></div><div className="imp-tax-card-grid">{tributos.map(t=><article className="imp-global-tax-card" key={t.id}><div className="imp-global-tax-top"><span className="imp-tax-icon"><Landmark size={15}/></span><div><strong>{t.nome}</strong><small>{t.sigla||'Sem sigla'}</small></div><span className="imp-active-dot"><i/>Ativo</span></div><div className="imp-global-tax-meta"><span><b>Esfera</b>{t.esfera||'Não informada'}</span><span><b>Periodicidade</b>{t.periodicidade||'Não informada'}</span></div></article>)}{!tributos.length&&<div className="imp-tax-catalog-empty"><Landmark size={22}/><strong>Nenhum tributo cadastrado</strong><span>Use “Novo tributo” para criar o primeiro cadastro.</span></div>}</div></section>
   <div className="imp-regime-grid">{REGIMES.map(r=><button key={r.value} className={`imp-regime-card ${r.className} ${regime===r.value?'active':''}`} onClick={()=>setRegime(r.value)}><span className="imp-regime-icon"><Landmark size={16}/></span><div><strong>{r.label}</strong><small>{r.value==='TODOS'?'Todas as empresas':`${visible.filter(x=>(x.regime_tributario||'').toUpperCase()===r.value).length} empresas`}</small></div></button>)}</div>
   <div className="panel imp-toolbar"><div className="empresa-search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar empresa, CNPJ ou nome fantasia..."/></div><div className="imp-competencia"><span>Competência</span><strong>{data.competencia.label}</strong></div></div>
   <div className="imp-list-head"><strong>Empresas</strong><span>{visible.length} empresa(s) exibida(s)</span></div>
   <div className="panel imp-table-wrap"><table className="imp-table"><thead><tr><th>Empresa</th><th>Regime</th><th>Tributos</th><th>Pendentes</th><th>Valor a pagar</th><th></th></tr></thead><tbody>{visible.map(item=><tr key={item.id} className="imp-row" onClick={()=>navigate(`/impostos/empresa/${item.id}`)}><td><div className="imp-company"><span><Building2 size={15}/></span><div><strong>{item.razao_social}</strong><small>{item.nome_fantasia||item.cnpj}</small></div></div></td><td><span className={`imp-regime-badge ${regimeClass(item.regime_tributario)}`}>{item.regime_tributario||'Não informado'}</span></td><td><span className="imp-number-badge">{item.tributos_vinculados}</span></td><td><span className={`imp-status ${item.impostos_pendentes?'pending':'done'}`}><i/> {item.impostos_pendentes?`${item.impostos_pendentes} pendente(s)`:'Em dia'}</span></td><td className="imp-money">{dinheiro(item.valor_a_pagar)}</td><td><ChevronRight size={16} className="imp-chevron"/></td></tr>)}{!visible.length&&<tr><td colSpan={6}><div className="imp-empty"><CheckCircle2 size={25}/><strong>Nenhuma empresa encontrada</strong><span>Ajuste os filtros para continuar.</span></div></td></tr>}</tbody></table></div>
   {novoOpen&&<div className="modal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setNovoOpen(false)}}><div className="modal imp-modal"><div className="modal-head"><div><span className="eyebrow">CADASTRO GLOBAL</span><h3>Novo tributo</h3></div><button className="icon-button" onClick={()=>setNovoOpen(false)}>×</button></div><div className="modal-body"><div className="form-grid"><label>Nome<input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Ex.: ICMS"/></label><label>Sigla<input value={sigla} onChange={e=>setSigla(e.target.value)} placeholder="Ex.: ICMS"/></label><label>Esfera<select value={esfera} onChange={e=>setEsfera(e.target.value)}><option value="">Selecione</option><option>Federal</option><option>Estadual</option><option>Municipal</option></select></label><label>Periodicidade<select value={periodicidade} onChange={e=>setPeriodicidade(e.target.value)}><option>Mensal</option><option>Anual</option><option>Conforme obrigação</option></select></label></div></div><div className="modal-actions"><button className="button secondary" onClick={()=>setNovoOpen(false)}>Cancelar</button><button className="button primary" disabled={saving} onClick={()=>void salvarTributo()}>{saving?'Salvando...':'Cadastrar tributo'}</button></div></div></div>}
 </div>;
}
