import {FormEvent,useState} from 'react';
import {Building2,Eye,EyeOff,LockKeyhole,Mail,ShieldCheck} from 'lucide-react';
import {useAuth} from '../../auth/AuthContext';
import {Link,useNavigate} from 'react-router-dom';

export function LoginPage(){
  const {login}=useAuth();const navigate=useNavigate();
  const [email,setEmail]=useState('admin@omega.local');const [senha,setSenha]=useState('Admin@123');const [mostrar,setMostrar]=useState(false);const [erro,setErro]=useState('');const [carregando,setCarregando]=useState(false);
  async function onSubmit(e:FormEvent){e.preventDefault();setErro('');setCarregando(true);try{const u=await login(email,senha);navigate(u.deve_trocar_senha?'/alterar-senha':'/');}catch(x){setErro(x instanceof Error?x.message:'Não foi possível entrar.')}finally{setCarregando(false)}}
  return <main className="login-page"><section className="login-brand"><div className="login-brand-mark">Ω</div><h1>ÔMEGA</h1><p>Gestão empresarial inteligente.</p><div className="login-points"><span><ShieldCheck size={16}/> Dados protegidos por autenticação</span><span><Building2 size={16}/> Empresas, certidões e pendências em um só lugar</span></div></section><section className="login-card"><div><span className="eyebrow">ACESSO SEGURO</span><h2>Entrar na plataforma</h2><p>Use seu e-mail e sua senha para continuar.</p></div>{erro&&<div className="form-error">{erro}</div>}<form onSubmit={onSubmit} className="login-form"><label>E-mail<div className="login-input"><Mail size={17}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/></div></label><label>Senha<div className="login-input"><LockKeyhole size={17}/><input type={mostrar?'text':'password'} value={senha} onChange={e=>setSenha(e.target.value)} autoComplete="current-password" required/><button type="button" className="password-toggle" onClick={()=>setMostrar(v=>!v)}>{mostrar?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label><button className="button primary login-submit" disabled={carregando}>{carregando?'Entrando...':'Entrar'}</button></form><div className="auth-links"><Link to="/registrar">Criar conta</Link><span>•</span><Link to="/esqueci-senha">Esqueci minha senha</Link></div><small className="login-help">Administrador inicial: <strong>admin@omega.local</strong>. A primeira entrada exige troca de senha.</small></section></main>;
}
