import {FormEvent,useState} from 'react';
import {Building2,Eye,EyeOff,LockKeyhole,Mail,UserRound,ShieldCheck} from 'lucide-react';
import {useNavigate,Link} from 'react-router-dom';
import {apiFetch} from '../../services/api/client';

export function RegisterPage(){
  const navigate=useNavigate();
  const [nome,setNome]=useState(''); const [email,setEmail]=useState(''); const [senha,setSenha]=useState(''); const [confirmar,setConfirmar]=useState('');
  const [mostrar,setMostrar]=useState(false); const [erro,setErro]=useState(''); const [ok,setOk]=useState(''); const [carregando,setCarregando]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setErro('');setOk('');if(senha!==confirmar){setErro('As senhas não conferem.');return;}setCarregando(true);try{await apiFetch('/api/v1/auth/registrar',{method:'POST',body:JSON.stringify({nome,email,senha,confirmar_senha:confirmar})});setOk('Conta criada com sucesso. Você já pode entrar na plataforma.');setTimeout(()=>navigate('/login'),900);}catch(x){setErro(x instanceof Error?x.message:'Não foi possível criar a conta. Verifique se a API está em execução.');}finally{setCarregando(false)}}
  return <main className="login-page"><section className="login-brand"><div className="login-brand-mark">Ω</div><h1>ÔMEGA</h1><p>Gestão empresarial inteligente.</p><div className="login-points"><span><ShieldCheck size={16}/> Cadastro protegido por autenticação</span><span><Building2 size={16}/> Empresas, certidões e pendências em um só lugar</span></div></section><section className="login-card"><div><span className="eyebrow">NOVO ACESSO</span><h2>Criar conta</h2><p>Cadastre seu acesso para utilizar a plataforma.</p></div>{erro&&<div className="form-error">{erro}</div>}{ok&&<div className="form-success">{ok}</div>}<form onSubmit={submit} className="login-form"><label>Nome<div className="login-input"><UserRound size={17}/><input value={nome} onChange={e=>setNome(e.target.value)} autoComplete="name" required/></div></label><label>E-mail<div className="login-input"><Mail size={17}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></div></label><label>Senha<div className="login-input"><LockKeyhole size={17}/><input type={mostrar?'text':'password'} value={senha} onChange={e=>setSenha(e.target.value)} autoComplete="new-password" minLength={8} required/><button type="button" className="password-toggle" onClick={()=>setMostrar(v=>!v)}>{mostrar?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label><label>Confirmar senha<div className="login-input"><LockKeyhole size={17}/><input type={mostrar?'text':'password'} value={confirmar} onChange={e=>setConfirmar(e.target.value)} autoComplete="new-password" minLength={8} required/></div></label><button className="button primary login-submit" disabled={carregando}>{carregando?'Criando conta...':'Criar conta'}</button></form><div className="auth-links"><Link to="/login">Já tenho uma conta</Link><span>•</span><Link to="/esqueci-senha">Esqueci minha senha</Link></div></section></main>;
}
