import {API_URL,apiFetch} from './client';

export type EmpresaDocumento={id:number;razao_social:string;nome_fantasia?:string|null;cnpj:string;regime_tributario?:string|null;ativo:number;municipio?:string|null;uf?:string|null;documentos_count:number};
export type CategoriaDocumento={id:number;empresa_id:number;categoria_pai_id:number|null;nome:string;descricao?:string|null;ordem:number;ativo:number;documentos_count:number};
export type Documento={id:number;empresa_id:number;categoria_id:number|null;tipo:string;nome:string;descricao?:string|null;categoria_nome?:string|null;versoes_count:number;ultima_versao?:number|null;ultima_versao_id?:number|null;nome_arquivo?:string|null;criado_em:string;atualizado_em:string};
export type Versao={id:number;documento_id:number;versao:number;nome_arquivo?:string|null;caminho_arquivo:string;extensao?:string|null;tamanho?:number|null;hash_arquivo?:string|null;mime_type?:string|null;observacao?:string|null;usuario_upload_id?:number|null;usuario_nome?:string|null;usuario_email?:string|null;criado_em:string};

export async function listarEmpresasDocumentacao(params:URLSearchParams=new URLSearchParams()){return apiFetch<{total:number;page:number;page_size:number;empresas:EmpresaDocumento[]}>(`/api/v1/documentacao/empresas?${params.toString()}`)}
export async function listarCategorias(empresaId:number){return apiFetch<{categorias:CategoriaDocumento[]}>(`/api/v1/documentacao/empresas/${empresaId}/categorias`)}
export async function criarCategoria(empresaId:number,data:{nome:string;descricao?:string;categoria_pai_id?:number|null}){return apiFetch<CategoriaDocumento>(`/api/v1/documentacao/empresas/${empresaId}/categorias`,{method:'POST',body:JSON.stringify(data)})}
export async function arquivarCategoria(id:number){return apiFetch<CategoriaDocumento>(`/api/v1/documentacao/categorias/${id}`,{method:'DELETE'})}
export async function arquivarDocumento(id:number){return apiFetch<Documento>(`/api/v1/documentacao/documentos/${id}`,{method:'DELETE'})}
export async function listarDocumentos(empresaId:number,categoriaId?:number){const q=categoriaId?`?categoria_id=${categoriaId}`:'';return apiFetch<{documentos:Documento[]}>(`/api/v1/documentacao/empresas/${empresaId}/documentos${q}`)}
export async function uploadDocumento(empresaId:number,categoriaId:number,nome:string,file:File,observacao?:string){const token=localStorage.getItem('omega_access_token');const fd=new FormData();fd.append('categoria_id',String(categoriaId));fd.append('nome_documento',nome);if(observacao) fd.append('observacao',observacao);fd.append('arquivo',file);const r=await fetch(`${API_URL}/api/v1/documentacao/empresas/${empresaId}/documentos/upload`,{method:'POST',headers:token?{Authorization:`Bearer ${token}`}:{},body:fd});const data=await r.json();if(!r.ok) throw new Error(typeof data?.detail==='string'?data.detail:'Falha no upload.');return data as Documento}
export async function listarVersoes(documentoId:number){return apiFetch<{versoes:Versao[]}>(`/api/v1/documentacao/documentos/${documentoId}/versoes`)}
export async function uploadNovaVersao(documentoId:number,file:File,observacao?:string){const token=localStorage.getItem('omega_access_token');const fd=new FormData();if(observacao) fd.append('observacao',observacao);fd.append('arquivo',file);const r=await fetch(`${API_URL}/api/v1/documentacao/documentos/${documentoId}/versoes`,{method:'POST',headers:token?{Authorization:`Bearer ${token}`}:{},body:fd});const data=await r.json();if(!r.ok) throw new Error(typeof data?.detail==='string'?data.detail:'Falha ao criar versão.');return data as Documento}
export function documentoVisualizarUrl(versaoId:number){return `${API_URL}/api/v1/documentacao/versoes/${versaoId}/visualizar`}
export function documentoDownloadUrl(versaoId:number){return `${API_URL}/api/v1/documentacao/versoes/${versaoId}/download`}
export async function baixarArquivo(versaoId:number){const token=localStorage.getItem('omega_access_token');const r=await fetch(documentoDownloadUrl(versaoId),{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!r.ok) throw new Error('Não foi possível baixar o arquivo.');return {blob:await r.blob(),name:r.headers.get('content-disposition')||'documento'};}

async function arquivoBlob(versaoId:number){const token=localStorage.getItem('omega_access_token');const r=await fetch(documentoDownloadUrl(versaoId),{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!r.ok) throw new Error('Não foi possível acessar o arquivo.');return {blob:await r.blob(),contentDisposition:r.headers.get('content-disposition')||''};}
export async function visualizarVersao(versaoId:number){const r=await arquivoBlob(versaoId);const url=URL.createObjectURL(r.blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);}
export async function baixarVersao(versaoId:number,nome?:string){const r=await arquivoBlob(versaoId);const url=URL.createObjectURL(r.blob);const a=document.createElement('a');a.href=url;a.download=nome||'documento';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
