import {apiFetch} from './client';

export type Tributo={id:number;nome:string;sigla?:string|null;esfera?:string|null;categoria?:string|null;periodicidade?:string|null;descricao?:string|null;ativo:number};
export type ImpostoEmpresa={id:number;razao_social:string;nome_fantasia?:string|null;cnpj:string;regime_tributario?:string|null;tributos_vinculados:number;impostos_pendentes:number;impostos_pagos:number;valor_a_pagar:number};
export type DashboardImpostos={empresas:ImpostoEmpresa[];indicadores:{total_empresas:number;empresas_configuradas:number;impostos_pendentes:number;impostos_pagos:number;valor_a_pagar:number;competencia:{ano:number;mes:number;label:string}};competencia:{ano:number;mes:number;label:string}};
export type EmpresaImpostos={empresa:{id:number;cnpj:string;razao_social:string;nome_fantasia?:string|null;regime_tributario?:string|null;municipio?:string|null;uf?:string|null;observacoes?:string|null};competencia:{ano:number;mes:number;label:string};resumo:{tributos_vinculados:number;informados:number;pendentes:number;pagos:number;valor_a_pagar:number};tributos:Array<{vinculo_id:number;tributo_id:number;nome:string;sigla?:string|null;esfera?:string|null;categoria?:string|null;periodicidade?:string|null;obrigatorio:number;vigencia_inicio?:string|null;vigencia_fim?:string|null;status_mensal?:string|null;valor?:number|null;data_vencimento?:string|null;data_pagamento?:string|null;numero_documento?:string|null;mensal_observacao?:string|null}>};

export const listarImpostos=(params:{q?:string;regime?:string;ano?:number;mes?:number}={})=>apiFetch<DashboardImpostos>(`/api/v1/impostos/dashboard?${new URLSearchParams(Object.entries(params).filter(([,v])=>v!==undefined&&v!=='').map(([k,v])=>[k,String(v)])).toString()}`);
export const listarTributos=()=>apiFetch<{tributos:Tributo[]}>('/api/v1/impostos/tributos');
export const criarTributo=(data:Partial<Tributo>)=>apiFetch<Tributo>('/api/v1/impostos/tributos',{method:'POST',body:JSON.stringify(data)});
export const obterEmpresaImpostos=(id:number,ano?:number,mes?:number)=>apiFetch<EmpresaImpostos>(`/api/v1/impostos/empresas/${id}?${new URLSearchParams({...(ano?{ano:String(ano)}:{}),...(mes?{mes:String(mes)}:{})}).toString()}`);
export const vincularTributo=(empresaId:number,data:{tributo_id:number;obrigatorio?:boolean;vigencia_inicio?:string|null;vigencia_fim?:string|null;observacao?:string|null})=>apiFetch('/api/v1/impostos/empresas/'+empresaId+'/tributos',{method:'POST',body:JSON.stringify(data)});
export const registrarImposto=(empresaId:number,data:{tributo_id:number;competencia_ano:number;competencia_mes:number;status:string;valor?:number|null;data_vencimento?:string|null;data_pagamento?:string|null;numero_documento?:string|null;observacao?:string|null})=>apiFetch('/api/v1/impostos/empresas/'+empresaId+'/mensais',{method:'POST',body:JSON.stringify(data)});
