import {useEffect,useMemo,useState} from 'react';
import {Building2,Plus,Search,RefreshCw,Eye,Edit3,CheckCircle2,XCircle,Users,LayoutGrid,List,Download,Filter,X} from 'lucide-react';
import {Link} from 'react-router-dom';
import {listarEmpresas,alterarRegime} from '../../services/api/empresas';
import type {Empresa} from '../../types';
import {Loading} from '../../components/ui/Loading';
import {ErrorState} from '../../components/ui/ErrorState';
import {EmpresaForm} from './EmpresaForm';

function regimeClass(regime?:string|null){
 const v=(regime||'').toLowerCase();
 if(v.includes('simples')) return 'regime simples';
 if(v.includes('presumido')) return 'regime presumido';
 if(v.includes('real')) return 'regime real';
 return 'regime';
}

export function EmpresasPage(){
 const [items,setItems]=useState<Empresa[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[err,setErr]=useState(''),[form,setForm]=useState(false),[regime,setRegime]=useState('TODOS'),[status,setStatus]=useState('TODOS'),[view,setView]=useState<'table'|'cards'>('table'),[regimeTarget,setRegimeTarget]=useState<Empresa|null>(null);
 const load=async()=>{setLoading(true);setErr('');try{setItems((await listarEmpresas()).empresas)}catch(x){setErr(x instanceof Error?x.message:'Erro ao carregar empresas.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const query=q.trim().toLowerCase();return items.filter(e=>{const matchesQ=!query||`${e.razao_social} ${e.nome_fantasia||''} ${e.cnpj} ${e.inscricao_estadual||''} ${e.nire||''}`.toLowerCase().includes(query);const matchesReg=regime==='TODOS'||(e.regime_tributario||'').toUpperCase()===regime;const matchesStatus=status==='TODOS'||(status==='ATIVA'?Boolean(e.ativo):!e.ativo);return matchesQ&&matchesReg&&matchesStatus}).sort((a,b)=>a.razao_social.localeCompare(b.razao_social,'pt-BR'))},[items,q,regime,status]);
 const total=items.length,ativas=items.filter(e=>e.ativo).length,inativas=total-ativas;
 const exportar=()=>{const header=['Razão Social','Nome Fantasia','CNPJ','Regime Tributário','Status','UF','Município'];const rows=filtered.map(e=>[e.razao_social,e.nome_fantasia||'',e.cnpj,e.regime_tributario||'',e.ativo?'Ativa':'Inativa',e.uf||'',e.municipio||'']);const csv=[header,...rows].map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob([`\ufeff${csv}`],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='empresas_omega.csv';a.click();URL.revokeObjectURL(a.href)};
 if(form)return <EmpresaForm onCancel={()=>setForm(false)} onCreated={()=>{setForm(false);void load()}}/>;
 async function salvarRegime(id:number,novo:string,mes:number,ano:number,observacao:string){setErr('');try{await alterarRegime(id,novo,mes,ano,observacao);setRegimeTarget(null);await load()}catch(x){setErr(x instanceof Error?x.message:'Falha ao alterar regime.')}}
 return <div className="page empresas-page"><div className="page-heading empresas-heading"><div><span className="eyebrow">CADASTRO EMPRESARIAL</span><h2><Building2 size={25}/> Empresas</h2><p>Gerencie o cadastro das empresas do seu portfólio em um só lugar.</p></div><div className="actions"><button className="button secondary" onClick={exportar}><Download size={15}/> Exportar</button><button className="button primary" onClick={()=>setForm(true)}><Plus size={15}/> Nova empresa</button></div></div>
 <div className="empresa-metrics"><div className="empresa-metric active"><span><Building2 size={19}/></span><div><strong>{total}</strong><small>Total de empresas</small></div></div><div className="empresa-metric"><span><CheckCircle2 size={19}/></span><div><strong>{ativas}</strong><small>Ativas</small></div></div><div className="empresa-metric"><span><XCircle size={19}/></span><div><strong>{inativas}</strong><small>Inativas</small></div></div><div className="empresa-metric"><span><Users size={19}/></span><div><strong>{items.filter(e=>Boolean(e.responsavel)).length}</strong><small>Com responsável</small></div></div></div>
 <div className="empresa-filters panel"><div className="empresa-search"><Search size={17}/><input value={q} placeholder="Buscar por razão social, nome fantasia, CNPJ, IE ou NIRE..." onChange={e=>setQ(e.target.value)}/></div><select value={regime} onChange={e=>setRegime(e.target.value)}><option value="TODOS">Todos os regimes</option><option value="SIMPLES NACIONAL">Simples Nacional</option><option value="LUCRO PRESUMIDO">Lucro Presumido</option><option value="LUCRO REAL">Lucro Real</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="TODOS">Todas as situações</option><option value="ATIVA">Ativas</option><option value="INATIVA">Inativas</option></select><button className="button secondary" onClick={()=>{setQ('');setRegime('TODOS');setStatus('TODOS')}}><Filter size={14}/> Limpar</button></div>
 <div className="empresa-list-head"><strong>{filtered.length} empresas encontradas</strong><div className="view-toggle"><button className={view==='table'?'active':''} onClick={()=>setView('table')} title="Tabela"><List size={16}/></button><button className={view==='cards'?'active':''} onClick={()=>setView('cards')} title="Cards"><LayoutGrid size={16}/></button></div></div>
 {loading?<Loading text="Carregando empresas..."/>:err?<ErrorState message={err} onRetry={load}/>:view==='table'?<div className="panel table-panel empresa-table-panel"><div className="table-wrap"><table><thead><tr><th>Razão Social</th><th>Nome Fantasia</th><th>CNPJ</th><th>Regime Tributário</th><th>Situação</th><th>Estado</th><th>Ações</th></tr></thead><tbody>{filtered.map(e=><tr key={e.id}><td><strong>{e.razao_social}</strong><small>{e.responsavel?`Resp.: ${e.responsavel}`:'Responsável não informado'}</small></td><td>{e.nome_fantasia||'—'}</td><td>{e.cnpj}</td><td><button className={`regime ${regimeClass(e.regime_tributario).replace('regime ','')} regime-clickable`} onClick={()=>setRegimeTarget(e)} title="Alterar regime tributário">{e.regime_tributario||'Não informado'}</button></td><td><span className={`status-pill ${e.ativo?'ok':'off'}`}><i/> {e.ativo?'Ativa':'Inativa'}</span></td><td>{e.uf||'—'}</td><td><div className="row-actions"><Link className="icon-button" to={`/empresas/${e.id}`} title="Abrir"><Eye size={15}/></Link><Link className="icon-button" to={`/empresas/${e.id}`} title="Editar"><Edit3 size={15}/></Link></div></td></tr>)}</tbody></table></div>{filtered.length===0&&<div className="empty"><Building2 size={32}/><strong>Nenhuma empresa encontrada</strong><span>Ajuste os filtros ou cadastre uma nova empresa.</span></div>}</div>:<div className="empresa-card-grid">{filtered.map(e=><article className="empresa-card" key={e.id}><div className="empresa-card-top"><span className="empresa-icon"><Building2 size={18}/></span><span className={`status-pill ${e.ativo?'ok':'off'}`}><i/> {e.ativo?'Ativa':'Inativa'}</span></div><h3>{e.razao_social}</h3><p>{e.nome_fantasia||'Sem nome fantasia'}</p><div className="empresa-card-data"><div><span>CNPJ</span><strong>{e.cnpj}</strong></div><div><span>Regime</span><button className={`${regimeClass(e.regime_tributario)} regime-clickable`} onClick={()=>setRegimeTarget(e)} title="Alterar regime tributário">{e.regime_tributario||'Não informado'}</button></div></div><div className="empresa-card-foot"><span>{e.municipio||'—'}{e.uf?`/${e.uf}`:''}</span><Link className="button secondary small" to={`/empresas/${e.id}`}>Abrir empresa <Eye size={13}/></Link></div></article>)}{filtered.length===0&&<div className="empty"><Building2 size={32}/><strong>Nenhuma empresa encontrada</strong><span>Ajuste os filtros ou cadastre uma nova empresa.</span></div>}</div>}
 {regimeTarget&&<RegimeModal atual={regimeTarget.regime_tributario||'Não informado'} onClose={()=>setRegimeTarget(null)} onSave={(novo,mes,ano,obs)=>void salvarRegime(regimeTarget.id,novo,mes,ano,obs)}/>}
 </div>;
}

function RegimeModal({atual,onClose,onSave}:{atual:string;onClose:()=>void;onSave:(novo:string,mes:number,ano:number,obs:string)=>void}){
 const hoje=new Date(); const [novo,setNovo]=useState(''); const [mes,setMes]=useState(String(hoje.getMonth()+1).padStart(2,'0')); const [ano,setAno]=useState(String(hoje.getFullYear())); const [obs,setObs]=useState(''); const opcoes=['Simples Nacional','Lucro Presumido','Lucro Real'];
 const confirmar=()=>{const m=Number(mes),a=Number(ano); if(!novo||novo===atual||m<1||m>12||a<2000||a>2100)return; onSave(novo,m,a,obs.trim())};
 return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal-card regime-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">ALTERAÇÃO TRIBUTÁRIA</span><h3>Alterar regime da empresa</h3></div><button className="icon-button" onClick={onClose}><X size={15}/></button></div><div className="regime-modal-body"><div className="regime-current"><span>Regime atual</span><strong>{atual}</strong></div><label>Novo regime<select value={novo} onChange={e=>setNovo(e.target.value)}><option value="">Selecione</option>{opcoes.map(o=><option key={o} value={o} disabled={o===atual}>{o}</option>)}</select></label><div className="regime-date-grid"><label>Mês de início<select value={mes} onChange={e=>setMes(e.target.value)}>{Array.from({length:12},(_,i)=>{const v=String(i+1).padStart(2,'0');return <option key={v} value={v}>{v}</option>})}</select></label><label>Ano de início<input value={ano} onChange={e=>setAno(e.target.value.replace(/\D/g,'').slice(0,4))}/></label></div><label>Observação <span className="optional">(opcional)</span><textarea value={obs} onChange={e=>setObs(e.target.value)} placeholder="Ex.: alteração por opção tributária."/></label><div className="regime-note">A alteração será registrada no histórico da empresa.</div></div><div className="modal-actions"><button className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" onClick={confirmar} disabled={!novo||novo===atual}>Confirmar alteração</button></div></div></div>
}
