import {useEffect,useState} from 'react';
import {Plus,ShieldCheck,UserCheck,UserX} from 'lucide-react';
import {apiFetch} from '../../services/api/client';

type U={id:number;nome:string;email:string;perfil:string;ativo:number;deve_trocar_senha:number;ultimo_login?:string|null};
export function UsuariosPage(){
 const [users,setUsers]=useState<U[]>([]);const [loading,setLoading]=useState(true);const [err,setErr]=useState('');const [form,setForm]=useState(false);const [nome,setNome]=useState('');const [email,setEmail]=useState('');const [senha,setSenha]=useState('');const [perfil,setPerfil]=useState('USUARIO');
 const load=async()=>{setLoading(true);try{setUsers((await apiFetch<{usuarios:U[]}>('/api/v1/auth/usuarios')).usuarios)}catch(x){setErr(x instanceof Error?x.message:'Erro ao carregar usuários.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 async function criar(){try{await apiFetch('/api/v1/auth/usuarios',{method:'POST',body:JSON.stringify({nome,email,senha,perfil})});setForm(false);setNome('');setEmail('');setSenha('');await load()}catch(x){setErr(x instanceof Error?x.message:'Erro ao criar usuário.')}}
 async function toggle(u:U){await apiFetch(`/api/v1/auth/usuarios/${u.id}/status`,{method:'PATCH',body:JSON.stringify({ativo:!Boolean(u.ativo)})});await load()}
 return <div className="page"><div className="page-heading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h2>Usuários</h2><p>Controle quem pode acessar a plataforma e qual perfil cada usuário possui.</p></div><button className="button primary" onClick={()=>setForm(true)}><Plus size={15}/> Novo usuário</button></div>{err&&<div className="form-error">{err}</div>}{form&&<div className="panel user-form-panel"><h3>Novo usuário</h3><div className="form-grid"><label>Nome<input value={nome} onChange={e=>setNome(e.target.value)}/></label><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha inicial<input type="password" value={senha} onChange={e=>setSenha(e.target.value)}/></label><label>Perfil<select value={perfil} onChange={e=>setPerfil(e.target.value)}><option value="USUARIO">Usuário</option><option value="ADMIN">Administrador</option></select></label></div><div className="actions"><button className="button secondary" onClick={()=>setForm(false)}>Cancelar</button><button className="button primary" onClick={criar}>Criar usuário</button></div></div>}<div className="panel table-panel">{loading?<div className="empty">Carregando...</div>:<div className="table-wrap"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>Status</th><th>Último acesso</th><th>Ações</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.nome}</strong><small>{u.email}</small></td><td><span className="badge neutral">{u.perfil}</span></td><td>{u.ativo?<span className="badge success"><UserCheck size={12}/> Ativo</span>:<span className="badge neutral"><UserX size={12}/> Inativo</span>}</td><td>{u.ultimo_login?new Date(u.ultimo_login.replace(' ','T')).toLocaleString('pt-BR'):'Nunca'}</td><td><button className="icon-button" title={u.ativo?'Desativar':'Ativar'} onClick={()=>toggle(u)}>{u.ativo?<UserX size={15}/>:<UserCheck size={15}/>}</button></td></tr>)}</tbody></table></div>}</div></div>;
}
