import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Folder,Plus,Upload,FileText,Download,Eye,History,Archive,ChevronRight,UsersRound,Building2} from 'lucide-react';
import {Link,useParams} from 'react-router-dom';
import {criarCategoria,listarCategorias,listarDocumentos,arquivarCategoria,uploadDocumento,listarVersoes,uploadNovaVersao,visualizarVersao,baixarVersao,type CategoriaDocumento,type Documento,type Versao} from '../../services/api/documentacao';
import {apiFetch} from '../../services/api/client';
import {Loading} from '../../components/ui/Loading';

export function EmpresaDocumentacaoPage(){
 const {id}=useParams();const empresaId=Number(id);const [empresa,setEmpresa]=useState<any>(null),[cats,setCats]=useState<CategoriaDocumento[]>([]),[selected,setSelected]=useState<number|null>(null),[docs,setDocs]=useState<Documento[]>([]),[loading,setLoading]=useState(true),[modal,setModal]=useState<'category'|'upload'|'version'|null>(null),[docTarget,setDocTarget]=useState<Documento|null>(null),[versions,setVersions]=useState<Versao[]>([]),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const [e,c]=await Promise.all([apiFetch<any>(`/api/v1/empresas/${empresaId}`),listarCategorias(empresaId)]);setEmpresa(e);setCats(c.categorias);if(selected){const r=await listarDocumentos(empresaId,selected);setDocs(r.documentos)}else setDocs([])}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar documentação.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[empresaId]);
 useEffect(()=>{if(selected)void listarDocumentos(empresaId,selected).then(r=>setDocs(r.documentos)).catch(e=>setError(e.message))},[selected]);
 const roots=useMemo(()=>cats.filter(c=>c.ativo&&c.categoria_pai_id===null),[cats]);const current=selected?cats.find(c=>c.id===selected):null;
 async function openVersions(doc:Documento){setDocTarget(doc);const r=await listarVersoes(doc.id);setVersions(r.versoes);setModal('version')}
 if(loading&&!empresa)return <div className="page"><Loading text="Carregando documentação..."/></div>;
 if(error&&!empresa)return <div className="page"><div className="panel empty"><strong>{error}</strong></div></div>;
 return <div className="page documentacao-detail-page">
  <div className="doc-detail-back"><Link to="/documentacao"><ArrowLeft size={15}/> Voltar para documentação</Link></div>
  <div className="page-heading"><div><span className="eyebrow">DOSSIÊ EMPRESARIAL</span><h2><Building2 size={24}/> {empresa?.razao_social}</h2><p>{empresa?.nome_fantasia||'Sem nome fantasia'} · {empresa?.cnpj}</p></div><div className="actions"><button className="button secondary" onClick={()=>setModal('category')}><Plus size={14}/> Nova pasta</button>{current&&<button className="button primary" onClick={()=>setModal('upload')}><Upload size={14}/> Enviar documento</button>}</div></div>
  {!selected?<>
   <div className="doc-folder-grid">{roots.map(c=>{const children=cats.filter(x=>x.ativo&&x.categoria_pai_id===c.id);return <button key={c.id} className="doc-folder-card" onClick={()=>setSelected(c.id)}><span className="doc-folder-icon"><Folder size={22}/></span><div><strong>{c.nome}</strong><small>{c.descricao||'Documentos desta pasta'}</small><em>{c.documentos_count} documento(s)</em>{children.length>0&&<span className="doc-subfolders">{children.slice(0,3).map(ch=><i key={ch.id}>{ch.nome}</i>)}{children.length>3&&<i>+{children.length-3}</i>}</span>}</div><ChevronRight size={17}/></button>})}<button className="doc-folder-card add" onClick={()=>setModal('category')}><span className="doc-folder-icon add"><Plus size={22}/></span><div><strong>Nova pasta</strong><small>Crie outro tipo de documento para esta empresa.</small></div></button></div>
   <div className="doc-folder-help panel"><UsersRound size={17}/><span><strong>Organização por tipo de documento</strong> — Cada pasta representa um grupo documental. Subpastas poderão ser criadas no futuro sem alterar a estrutura do sistema.</span></div>
  </>:<>
   <div className="doc-breadcrumb"><button onClick={()=>setSelected(null)}><Folder size={15}/> Documentação</button><ChevronRight size={13}/><strong>{current?.nome}</strong></div>
   <div className="doc-category-header panel"><div><span className="doc-folder-icon"><Folder size={20}/></span><div><strong>{current?.nome}</strong><small>{current?.descricao}</small></div></div><div className="actions"><button className="button secondary" onClick={()=>{if(confirm('Arquivar esta pasta? Ela deixará de receber novos uploads.'))void arquivarCategoria(current!.id).then(()=>{setSelected(null);void load()})}}><Archive size={13}/> Arquivar pasta</button><button className="button primary" onClick={()=>setModal('upload')}><Upload size={13}/> Enviar documento</button></div></div>
   <div className="panel doc-list-panel"><div className="section-title-row"><div><h3><FileText size={17}/> Documentos</h3><span>{docs.length} documento(s) nesta pasta</span></div></div>{docs.length===0?<div className="empty"><Folder size={28}/><strong>Nenhum documento nesta pasta</strong><span>Envie o primeiro arquivo para esta categoria.</span></div>:<div className="doc-items">{docs.map(d=><div className="doc-item" key={d.id}><span className="doc-file-icon"><FileText size={18}/></span><div className="doc-item-main"><strong>{d.nome}</strong><small>{d.nome_arquivo||'Sem arquivo'} · {d.versoes_count} versão(ões)</small></div><div className="doc-item-actions"><button className="icon-button" title="Histórico" onClick={()=>void openVersions(d)}><History size={15}/></button>{d.ultima_versao&&<><button className="icon-button" onClick={()=>void visualizarVersao(d.ultima_versao_id!)} title="Visualizar"><Eye size={15}/></button><button className="icon-button" onClick={()=>void baixarVersao(d.ultima_versao_id!,d.nome_arquivo||d.nome)} title="Baixar"><Download size={15}/></button></>}<button className="button secondary small" onClick={()=>{setDocTarget(d);setModal('version')}}>Nova versão</button></div></div>)}</div>}</div>
  </>}
  {modal==='category'&&<Modal title="Nova pasta" onClose={()=>setModal(null)}><CategoryForm parents={roots} onCancel={()=>setModal(null)} onSave={async(data)=>{await criarCategoria(empresaId,data);setModal(null);await load()}}/></Modal>}
  {modal==='upload'&&current&&<Modal title={`Enviar documento · ${current.nome}`} onClose={()=>setModal(null)}><UploadForm onCancel={()=>setModal(null)} onSave={async(data)=>{await uploadDocumento(empresaId,current.id,data.nome,data.file,data.observacao);setModal(null);const r=await listarDocumentos(empresaId,current.id);setDocs(r.documentos);await load()}}/></Modal>}
  {modal==='version'&&docTarget&&<Modal title={`Histórico · ${docTarget.nome}`} onClose={()=>setModal(null)}><div className="version-list">{versions.length===0?<span>Nenhuma versão registrada.</span>:versions.map(v=><div className="version-row" key={v.id}><div><strong>Versão {v.versao}</strong><small>{v.nome_arquivo} · {v.usuario_nome||'Usuário'} · {v.criado_em}</small></div><div className="download-actions"><button className="icon-button" onClick={()=>void visualizarVersao(v.id)}><Eye size={14}/></button><button className="icon-button" onClick={()=>void baixarVersao(v.id,v.nome_arquivo||`documento_v${v.versao}`)}><Download size={14}/></button></div></div>)}</div><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Fechar</button><button className="button primary" onClick={()=>setModal('version')}>Nova versão</button></div>{docTarget&&<InlineVersionForm documentId={docTarget.id} onDone={async()=>{const r=await listarVersoes(docTarget.id);setVersions(r.versoes);const d=await listarDocumentos(empresaId,current!.id);setDocs(d.documentos)}}/></Modal>}
 </div>
}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:any}){return <div className="modal-backdrop"><div className="modal-card"><div className="modal-head"><h3>{title}</h3><button className="icon-button" onClick={onClose}>×</button></div>{children}</div></div>}
function CategoryForm({onCancel,onSave,parents}:{onCancel:()=>void;onSave:(d:{nome:string;descricao?:string;categoria_pai_id?:number|null})=>Promise<void>;parents:CategoriaDocumento[]}){const [nome,setNome]=useState(''),[descricao,setDescricao]=useState(''),[parent,setParent]=useState('');return <div className="modal-form"><label>Nome da pasta<input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Ex.: Contratos"/></label><label>Pasta pai (opcional)<select value={parent} onChange={e=>setParent(e.target.value)}><option value="">Pasta principal</option>{parents.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label>Descrição<textarea value={descricao} onChange={e=>setDescricao(e.target.value)} placeholder="Finalidade da pasta"/></label><div className="modal-actions"><button className="button secondary" onClick={onCancel}>Cancelar</button><button className="button primary" disabled={!nome.trim()} onClick={()=>void onSave({nome,descricao,categoria_pai_id:parent?Number(parent):null})}>Criar pasta</button></div></div>}
function UploadForm({onCancel,onSave}:{onCancel:()=>void;onSave:(d:{nome:string;file:File;observacao?:string})=>Promise<void>}){const [nome,setNome]=useState(''),[observacao,setObservacao]=useState(''),[file,setFile]=useState<File|null>(null);return <div className="modal-form"><label>Nome do documento<input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Ex.: Contrato Social"/></label><label>Arquivo<input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>Limite padrão: 25 MB.</small></label><label>Observação<textarea value={observacao} onChange={e=>setObservacao(e.target.value)}/></label><div className="modal-actions"><button className="button secondary" onClick={onCancel}>Cancelar</button><button className="button primary" disabled={!nome.trim()||!file} onClick={()=>void onSave({nome,file:file!,observacao})}>Enviar documento</button></div></div>}
function InlineVersionForm({documentId,onDone}:{documentId:number;onDone:()=>Promise<void>}){const [file,setFile]=useState<File|null>(null),[sending,setSending]=useState(false);return <div className="version-upload"><h4>Adicionar nova versão</h4><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="button primary" disabled={!file||sending} onClick={async()=>{setSending(true);try{await uploadNovaVersao(documentId,file!);await onDone()}finally{setSending(false)}}}>{sending?'Enviando...':'Enviar nova versão'}</button></div>}
